/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as AuctionsAuctionUuidRouteRouteImport } from './routes/auctions/$auctionUuid/route'
import { Route as AuctionsAuctionUuidIndexRouteImport } from './routes/auctions/$auctionUuid/index'
import { Route as AuctionsAuctionUuidBetsRouteImport } from './routes/auctions/$auctionUuid/bets'
import { Route as AuctionsAuctionUuidBidRouteImport } from './routes/auctions/$auctionUuid/bid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionUuidRouteRoute =
  AuctionsAuctionUuidRouteRouteImport.update({
    id: '/auctions/$auctionUuid',
    path: '/auctions/$auctionUuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuctionsAuctionUuidIndexRoute =
  AuctionsAuctionUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuctionsAuctionUuidRouteRoute,
  } as any)
const AuctionsAuctionUuidBetsRoute = AuctionsAuctionUuidBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AuctionsAuctionUuidRouteRoute,
} as any)
const AuctionsAuctionUuidBidRoute = AuctionsAuctionUuidBidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => AuctionsAuctionUuidRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRouteRouteWithChildren
  '/auctions/': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bets': typeof AuctionsAuctionUuidBetsRoute
  '/auctions/$auctionUuid/bid': typeof AuctionsAuctionUuidBidRoute
  '/auctions/$auctionUuid/': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bets': typeof AuctionsAuctionUuidBetsRoute
  '/auctions/$auctionUuid/bid': typeof AuctionsAuctionUuidBidRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRouteRouteWithChildren
  '/auctions/': typeof AuctionsIndexRoute
  '/auctions/$auctionUuid/bets': typeof AuctionsAuctionUuidBetsRoute
  '/auctions/$auctionUuid/bid': typeof AuctionsAuctionUuidBidRoute
  '/auctions/$auctionUuid/': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions/$auctionUuid'
    | '/auctions/'
    | '/auctions/$auctionUuid/bets'
    | '/auctions/$auctionUuid/bid'
    | '/auctions/$auctionUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/auctions/$auctionUuid/bets'
    | '/auctions/$auctionUuid/bid'
    | '/auctions/$auctionUuid'
  id:
    | '__root__'
    | '/'
    | '/auctions/$auctionUuid'
    | '/auctions/'
    | '/auctions/$auctionUuid/bets'
    | '/auctions/$auctionUuid/bid'
    | '/auctions/$auctionUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsAuctionUuidRouteRoute: typeof AuctionsAuctionUuidRouteRouteWithChildren
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid': {
      id: '/auctions/$auctionUuid'
      path: '/auctions/$auctionUuid'
      fullPath: '/auctions/$auctionUuid'
      preLoaderRoute: typeof AuctionsAuctionUuidRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid/': {
      id: '/auctions/$auctionUuid/'
      path: '/'
      fullPath: '/auctions/$auctionUuid/'
      preLoaderRoute: typeof AuctionsAuctionUuidIndexRouteImport
      parentRoute: typeof AuctionsAuctionUuidRouteRoute
    }
    '/auctions/$auctionUuid/bets': {
      id: '/auctions/$auctionUuid/bets'
      path: '/bets'
      fullPath: '/auctions/$auctionUuid/bets'
      preLoaderRoute: typeof AuctionsAuctionUuidBetsRouteImport
      parentRoute: typeof AuctionsAuctionUuidRouteRoute
    }
    '/auctions/$auctionUuid/bid': {
      id: '/auctions/$auctionUuid/bid'
      path: '/bid'
      fullPath: '/auctions/$auctionUuid/bid'
      preLoaderRoute: typeof AuctionsAuctionUuidBidRouteImport
      parentRoute: typeof AuctionsAuctionUuidRouteRoute
    }
  }
}

interface AuctionsAuctionUuidRouteRouteChildren {
  AuctionsAuctionUuidBetsRoute: typeof AuctionsAuctionUuidBetsRoute
  AuctionsAuctionUuidBidRoute: typeof AuctionsAuctionUuidBidRoute
  AuctionsAuctionUuidIndexRoute: typeof AuctionsAuctionUuidIndexRoute
}

const AuctionsAuctionUuidRouteRouteChildren: AuctionsAuctionUuidRouteRouteChildren =
  {
    AuctionsAuctionUuidBetsRoute: AuctionsAuctionUuidBetsRoute,
    AuctionsAuctionUuidBidRoute: AuctionsAuctionUuidBidRoute,
    AuctionsAuctionUuidIndexRoute: AuctionsAuctionUuidIndexRoute,
  }

const AuctionsAuctionUuidRouteRouteWithChildren =
  AuctionsAuctionUuidRouteRoute._addFileChildren(
    AuctionsAuctionUuidRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsAuctionUuidRouteRoute: AuctionsAuctionUuidRouteRouteWithChildren,
  AuctionsIndexRoute: AuctionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
